{{- with .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger-lens-sync-chart.fullname" $ }}-secret
  labels:
    {{- include "ledger-lens-sync-chart.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}