apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger-lens-sync-chart.fullname" . }}
  labels:
    {{- include "ledger-lens-sync-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ledger-lens-sync-chart.selectorLabels" . | nindent 4 }}
